//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demka3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.ProductsMaterial = new HashSet<ProductsMaterial>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int MaterialType_ID { get; set; }
        public decimal Cost { get; set; }
        public int Remains { get; set; }
        public int MinQuantity { get; set; }
        public int QuantityPerPackage { get; set; }
        public int UnitID { get; set; }
    
        public virtual MaterialsType MaterialsType { get; set; }
        public virtual UnitsOfMeasurement UnitsOfMeasurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsMaterial> ProductsMaterial { get; set; }
    }
}
